spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/wishlist
    username: postgres
    password: ${DB_PASSWORD:mysecretpassword}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
  application:
    name: wishlist
