CREATE TABLE users (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(100) NOT NULL UNIQUE,
    password_hash VARCHAR(75) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT  CURRENT_TIMESTAMP
);